// Generated by CoffeeScript 1.9.3
(function() {
  var CrowdBackend,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  CrowdBackend = (function() {
    function CrowdBackend(params1) {
      this.params = params1;
      this.search = bind(this.search, this);
      this.del = bind(this.del, this);
      this.compare = bind(this.compare, this);
      this.bind = bind(this.bind, this);
      this.modifyDN = bind(this.modifyDN, this);
      this.modify = bind(this.modify, this);
      this.add = bind(this.add, this);
    }

    CrowdBackend.prototype.add = function(req, res, next) {
      console.log('add');
      console.log(req);
      console.log(res);
      res.end();
      return next();
    };

    CrowdBackend.prototype.modify = function(req, res, next) {
      console.log('modify');
      console.log(req);
      console.log(res);
      res.end();
      return next();
    };

    CrowdBackend.prototype.modifyDN = function(req, res, next) {
      console.log('modifyDN');
      console.log(req);
      console.log(res);
      res.end();
      return next();
    };

    CrowdBackend.prototype.bind = function(req, res, next) {
      console.log('bind');
      console.log(req);
      console.log(res);
      res.end();
      return next();
    };

    CrowdBackend.prototype.compare = function(req, res, next) {
      console.log('compare');
      console.log(req);
      console.log(res);
      res.end(false);
      return next();
    };

    CrowdBackend.prototype.del = function(req, res, next) {
      console.log('del');
      console.log(req);
      console.log(res);
      res.end();
      return next();
    };

    CrowdBackend.prototype.search = function(req, res, next) {
      console.log('search');
      console.log(req);
      console.log(res);
      res.end();
      return next();
    };

    return CrowdBackend;

  })();

  module.exports.createBackend = function(params) {
    return new CrowdBackend(params);
  };

}).call(this);
