// Generated by CoffeeScript 1.9.3
(function() {
  var CrowdBackend, ldapjs,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ldapjs = require('ldapjs');

  CrowdBackend = (function() {
    function CrowdBackend(params1) {
      this.params = params1;
      this.search = bind(this.search, this);
      this.bind = bind(this.bind, this);
    }

    CrowdBackend.prototype.bind = function(req, res, next) {
      res.end();
      return next();
    };

    CrowdBackend.prototype.search = function(req, res, next) {
      res.end();
      return next();
    };

    CrowdBackend.prototype.add = function(req, res, next) {
      return next(new ldapjs.OtherError('not implemented'));
    };

    CrowdBackend.prototype.modify = function(req, res, next) {
      return next(new ldapjs.OtherError('not implemented'));
    };

    CrowdBackend.prototype.modifyDN = function(req, res, next) {
      return next(new ldapjs.OtherError('not implemented'));
    };

    CrowdBackend.prototype.compare = function(req, res, next) {
      return next(new ldapjs.OtherError('not implemented'));
    };

    CrowdBackend.prototype.del = function(req, res, next) {
      return next(new ldapjs.OtherError('not implemented'));
    };

    return CrowdBackend;

  })();

  module.exports.createBackend = function(params) {
    return new CrowdBackend(params);
  };

}).call(this);
